# Generated by Django 6.0 on 2025-12-24 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masked_word', models.CharField(max_length=100)),
                ('guessed_letters', models.CharField(max_length=26)),
                ('lives', models.IntegerField()),
                ('result', models.CharField(choices=[('VICTORY', 'Victory'), ('DEFEAT', 'Defeat'), ('CORRECT', 'Correct'), ('INCORRECT', 'Incorrect')], max_length=10, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.word')),
            ],
        ),
    ]
