# Generated by Django 6.0 on 2025-12-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_alter_word_difficulty_gamesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='guessed_letters',
            field=models.CharField(default='', max_length=26),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='result',
            field=models.CharField(choices=[('START', 'Start'), ('VICTORY', 'Victory'), ('DEFEAT', 'Defeat'), ('CORRECT', 'Correct'), ('INCORRECT', 'Incorrect')], default='START', max_length=10),
        ),
    ]
