# Generated by Django 6.0 on 2025-12-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_alter_gamesession_guessed_letters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='guessed_letters',
            field=models.CharField(blank=True, default='', max_length=26),
        ),
    ]
